spring.datasource.url=jdbc:postgresql://postgresdb-1.cpow820somw9.ap-south-1.rds.amazonaws.com:5432/postgres
server.port=8089
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=public
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto = create-drop
#create DB if not present
#spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto = update

